dist: bionic
language: node_js
node_js:
  - 12
  - 13
  - 14
branches:
  only:
    - master
before_install:
  - sudo apt-get install -y libffi-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  - npm install -g cmake-js
install:
  - ./build_ci.sh
script: true
cache: npm
